version: '3'

services:
  db:
    container_name: ${MONGODB_DATABASE}
    image: mongo:6.0-jammy
    volumes:
      - poke-vol:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD} 
    command: ['--auth']  
    # ports:
    #   - 27018:27017
    restart: always

  mongo-express:
    depends_on:
      - db
    image: mongo-express:1.0.0-alpha.4
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGODB_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: ${MONGODB_DATABASE}
    ports:
      - 9090:8081 
    restart: always

  poke-app:
    depends_on:
      - db
    image: klerith/pokemon-nest-app:1.0.0
    ports:
      - 3000:3000
    environment:
      MONGODB: mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@${MONGODB_DATABASE}:27017
      DB_NAME: ${MONGODB_DATABASE}
    restart: always

volumes:
  poke-vol:
    external: false