name: Docker Image CI

on:
  push:
    branches: [ "action" ]
  pull_request:
    branches: [ "action" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: ckeckout code
      uses: actions/checkout@v3
      with: 
        fetch-depth: 0

    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}} 
        DOCKER_PASS: ${{secrets.DOCKER_PASSWORD}}    
      run: |
        echo "Starting login"
        docker login -u $DOCKER_USER -p $DOCKER_PASS
        echo "ending login"
        
    # - name: Build the Docker image
      # run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
