name: Docker Image CI

on:
  push:
    branches: [ "action" ]
  pull_request:
    branches: [ "action" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: ckeckout code
      uses: actions/checkout@v3
      with: 
        fetch-depth: 0

    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}} 
        DOCKER_PASS: ${{secrets.DOCKER_PASSWORD}}    
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASS

    - name: build docker image
      run:  |
        docker buildx b --platform linux/amd64,linux/arm64 -t fjmedina21/docker-graphql:0.0.2 .
    
    - name: push docker image
      run:  |
        docker push -t fjmedina21/docker-graphql:0.0.2 .
        
    # - name: Build the Docker image
      # run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)