name: Docker Image CI

on:
  push:
    branches: [ "action" ]
  pull_request:
    branches: [ "action" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: ckeckout code
      uses: actions/checkout@v3
      with: 
        fetch-depth: 0
    - name: Git Semantic Version
      uses: PaulHatch/semantic-version@v4.0.3
      with: 
        major_patter: "major:"
        minor_patter: "feat:"
        format: "${major}.${minor}.${patch}-prerelease${increment}"
      id: version
            
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}} 
        DOCKER_PASS: ${{secrets.DOCKER_PASSWORD}}    
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASS
        
    - name: build docker image
      env: 
        NEW_VERSION: ${{steps.version.outputs.version}}
      run:  |
        docker build -t fjmedina21/docker-graphql:$NEW_VERSION .
        docker build -t fjmedina21/docker-graphql .
    
    - name: push docker image
      env: 
        NEW_VERSION: ${{steps.version.outputs.version}}
      run:  |
        docker push fjmedina21/docker-graphql:$NEW_VERSION 
        docker push fjmedina21/docker-graphql
        
    # - name: Build the Docker image
      # run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
